# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Build App Only without Archive"
  lane :build_only do
    build_ios_app(
      project: "iTunesSearch.xcodeproj",
      configuration: "Debug",
      scheme: "iTunesSearch",
      clean: true,
      skip_archive: true,
      skip_codesigning: true,
      sdk: "iOS 13.0"
    )
  end

  desc "Unit Test"
  lane :unit_test do
    run_tests(
      scheme: "iTunesSearch",
      parallel_testing: false,
    )
  end
end
